-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 13:29:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sdp_file
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sdp_file
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sdp_file;
USE sdp_file;

-- -----------------------------------------------------
-- Table `sdp_file`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sdp_file.user
(
    `id` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdp_file`.`FOLDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sdp_file.folder
(
    `id`         VARCHAR(36)                          NOT NULL,
    `name`       VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
    `created_at` DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME                             NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `USER_id`    VARCHAR(36)                          NOT NULL,
    `FOLDER_id`  VARCHAR(36)                          NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_FOLDER_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES sdp_file.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_FOLDER_FOLDER1`
        FOREIGN KEY (`FOLDER_id`)
            REFERENCES sdp_file.folder (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_FOLDER_USER1_idx` ON sdp_file.folder (`USER_id` ASC) VISIBLE;

CREATE INDEX `fk_FOLDER_FOLDER1_idx` ON sdp_file.folder (`FOLDER_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sdp_file`.`FILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sdp_file.file
(
    `id`            VARCHAR(36)                          NOT NULL,
    `original_name` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
    `save_location` VARCHAR(1000)                        NOT NULL,
    `type`          VARCHAR(100)                         NOT NULL,
    `bytes`         INT UNSIGNED                         NOT NULL,
    `created_at`    DATETIME                             NULL DEFAULT CURRENT_TIMESTAMP,
    `USER_id`       VARCHAR(36)                          NOT NULL,
    `FOLDER_id`     VARCHAR(36)                          NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_ATTACHMENT_USER1`
        FOREIGN KEY (`USER_id`)
            REFERENCES sdp_file.user (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ATTACHMENT_FOLDER2`
        FOREIGN KEY (`FOLDER_id`)
            REFERENCES sdp_file.folder (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_ATTACHMENT_USER1_idx` ON sdp_file.file (`USER_id` ASC) VISIBLE;

CREATE INDEX `fk_ATTACHMENT_FOLDER2_idx` ON sdp_file.file (`FOLDER_id` ASC) VISIBLE;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
